baud_rate: 9600
com_port: COM14
invert_sliders: false
noise_reduction: high
slider_mapping:
  0: Spotify.exe
  1: master
  2: mic
  3: DungeonCrawler.exe
  4: firefox.exe
  5: discord.exe
  6: spotify.exe
